version: '3.1'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: app
    ports:
      - 4000:4000
  db:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: postgres-dev
      POSTGRES_PASSWORD: s3cr3tp4ssw0rd
    ports:
      - "5432:5432"
    command: postgres -c max_connections=1000

