version: "3.7"

services:
  database:
    image: postgres:12.3-alpine
    restart: always
    container_name: story-db
    hostname: database
    networks:
      - internal_network
    environment:
      - "POSTGRES_USER=${POSTGRES_USER}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_DB=${POSTGRES_DB}"
    command: ["-p", "${POSTGRES_PORT}"]
    volumes:
      - pgsql-data:/var/lib/postgresql/data

  server:
    build: "."
    restart: always
    privileged: false
    container_name: story-server
    networks:
      - internal_network
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      - DB_HOST=database
    volumes:
      - .env.dev:/app/.env.dev

networks:
  internal_network:

volumes:
  pgsql-data:
